Default: &defaults
  database: dohaskell.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: dohaskell_test.sqlite3
  <<: *defaults

Staging:
  database: dohaskell_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: dohaskell_production.sqlite3
  poolsize: 100
  <<: *defaults
