#!/bin/bash

BROWSER=google-chrome  # Browser to open spec in after generation.
SPEC_HOME=home.html    # The root html file of the spec.
HTML_DIR=.html         # The home of .html files.

hash pandoc 2>/dev/null || { echo >&2 "pandoc missing: cabal install pandoc"; exit 1; }
mkdir -p $HTML_DIR

for markdown in $(find . -name "*.md"); do
   html=$HTML_DIR/${markdown#./}
   html=${html%.md}.html
   echo "pandoc $markdown -o $html"
   pandoc $markdown -o $html
   echo Last updated: $(date) >> $html
done

echo "`which $BROWSER` $HTML_DIR/$SPEC_HOME"
`which $BROWSER` $HTML_DIR/$SPEC_HOME
